import React, { useState } from 'react';
import { ActivityIndicator, Image, ImageBackground, Platform, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { colors } from '../theme';
type User = { id: string; email: string; displayName: string; avatarUrl: string | null };
const baseUrl = Platform.OS === 'web' ? '' : (process.env.EXPO_PUBLIC_API_URL ?? '');
const appIcon = require('../../assets/branding/footandhealth-app-icon.png');
const background = require('../../assets/branding/wellness-background-v1.png');
export function AuthScreen({ onAuthenticated }: { onAuthenticated: (user: User, isNew: boolean) => void }) {
  const [mode, setMode] = useState<'login' | 'register'>('login'); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [name, setName] = useState(''); const [loading, setLoading] = useState(false); const [error, setError] = useState('');
  const submit = async () => { setError(''); setLoading(true); try { const response = await fetch(`${baseUrl}/api/auth/${mode === 'login' ? 'login' : 'register'}`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ email, password, displayName: name }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error || 'İşlem tamamlanamadı.'); onAuthenticated(data.user, mode === 'register'); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Bağlantı kurulamadı.'); } finally { setLoading(false); } };
  const google = () => { if (Platform.OS !== 'web') { setError('Google girişi bu Vercel web uygulamasında kullanılabilir.'); return; } window.location.assign('/api/auth/google/start'); };
  return <ImageBackground source={background} resizeMode="cover" style={s.page} imageStyle={s.bg}><View style={s.hero}><Image source={appIcon} style={s.mark}/><Text style={s.brand}>GIDA PUSULASI</Text><Text style={s.title}>{mode === 'login' ? 'Tekrar hoş geldin' : 'Sağlıklı yolculuğuna başla'}</Text><Text style={s.copy}>Taradığın ürünleri ve sağlık profilini yalnızca sen görürsün.</Text></View><View style={s.card}>{mode === 'register' && <Field label="Adın" value={name} onChangeText={setName} placeholder="Adın" autoCapitalize="words"/>}<Field label="E-posta" value={email} onChangeText={setEmail} placeholder="ornek@email.com" keyboardType="email-address" autoCapitalize="none"/><Field label="Parola" value={password} onChangeText={setPassword} placeholder="En az 8 karakter" secureTextEntry/>{error ? <Text style={s.error}>{error}</Text> : null}<Pressable onPress={submit} disabled={loading} style={[s.primary, loading && s.disabled]}>{loading ? <ActivityIndicator color="#fff"/> : <Text style={s.primaryText}>{mode === 'login' ? 'Giriş yap' : 'Hesabımı oluştur'}  →</Text>}</Pressable><View style={s.or}><View style={s.line}/><Text style={s.orText}>veya</Text><View style={s.line}/></View><Pressable onPress={google} style={s.google}><Text style={s.googleG}>G</Text><Text style={s.googleText}>Google ile devam et</Text></Pressable><Pressable onPress={() => { setMode(mode === 'login' ? 'register' : 'login'); setError(''); }}><Text style={s.switch}>{mode === 'login' ? 'Hesabın yok mu? Hesap oluştur' : 'Zaten hesabın var mı? Giriş yap'}</Text></Pressable></View><Text style={s.note}>Bu uygulama tıbbi tanı veya tedavi yerine geçmez.</Text></ImageBackground>;
}
function Field(props: React.ComponentProps<typeof TextInput> & { label: string }) { const { label, ...input } = props; return <View style={s.field}><Text style={s.label}>{label}</Text><TextInput {...input} style={s.input} placeholderTextColor="#90A09A" /></View>; }
const s = StyleSheet.create({ page:{flex:1,justifyContent:'center',padding:24,backgroundColor:'#F7F5EC'},bg:{opacity:.28},hero:{alignItems:'center',marginBottom:25},mark:{width:58,height:58,borderRadius:20},brand:{fontWeight:'900',letterSpacing:1.6,color:colors.brand,fontSize:14,marginTop:9},title:{fontSize:29,lineHeight:35,fontWeight:'900',color:colors.ink,textAlign:'center',marginTop:14},copy:{color:colors.muted,textAlign:'center',lineHeight:21,marginTop:8},card:{backgroundColor:'rgba(255,255,255,.94)',borderRadius:28,padding:20,gap:14,shadowColor:'#123',shadowOpacity:.07,shadowRadius:18,elevation:2},field:{gap:6},label:{fontSize:13,color:colors.ink,fontWeight:'800'},input:{height:49,borderWidth:1,borderColor:'#DFE6DF',borderRadius:14,paddingHorizontal:14,color:colors.ink,fontSize:16,backgroundColor:'#FBFCF9'},primary:{height:53,borderRadius:16,alignItems:'center',justifyContent:'center',backgroundColor:colors.brand,marginTop:3},primaryText:{color:'#fff',fontWeight:'900',fontSize:16},disabled:{opacity:.65},or:{flexDirection:'row',alignItems:'center',gap:10},line:{height:1,flex:1,backgroundColor:'#E3E7E1'},orText:{fontSize:12,color:colors.muted},google:{height:52,borderWidth:1,borderColor:'#D9E0DA',borderRadius:16,flexDirection:'row',alignItems:'center',justifyContent:'center',gap:10},googleG:{fontSize:20,fontWeight:'900',color:'#4285F4'},googleText:{fontWeight:'800',color:colors.ink},switch:{color:colors.brand,fontWeight:'800',fontSize:13,textAlign:'center',marginTop:2},error:{color:'#B12B2B',fontWeight:'700',fontSize:13,lineHeight:18},note:{fontSize:11,textAlign:'center',color:colors.muted,marginTop:18} });
