import { Ionicons } from '@expo/vector-icons';
import React, { useEffect, useState } from 'react';
import { Image, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { colors } from '../theme';
type Info = { name?: string; image?: string; brand?: string };
export function HistoryScreen({ scans, onOpen }: { scans: string[]; onOpen: (code: string) => void }) {
  const [filter, setFilter] = useState('Tümü');
  if (!scans.length) return <View style={s.empty}><Ionicons name="time-outline" size={38} color={colors.brand}/><Text style={s.emptyTitle}>Henüz geçmiş ürün yok</Text><Text style={s.emptyText}>Taradığın ürünler burada listelenecek.</Text></View>;
  return <ScrollView contentContainerStyle={s.page} showsVerticalScrollIndicator={false}><View style={s.top}><View><Text style={s.kicker}>ÜRÜN ARŞİVİN</Text><Text style={s.title}>Geçmiş ürünler</Text></View><View style={s.total}><Text style={s.totalText}>{scans.length}</Text></View></View><View style={s.filters}>{['Tümü', 'Uygun', 'Dikkat', 'Uygun Değil'].map(item => <Pressable key={item} onPress={() => setFilter(item)} style={[s.filter, filter === item && s.filterOn]}><Text style={[s.filterText, filter === item && s.filterTextOn]}>{item}</Text></Pressable>)}</View><View style={s.list}>{scans.map((code, index) => <HistoryRow key={code} code={code} index={index} onOpen={onOpen}/>)}</View></ScrollView>;
}
function HistoryRow({ code, index, onOpen }: { code: string; index: number; onOpen: (code: string) => void }) {
  const [info, setInfo] = useState<Info>({}); useEffect(() => { let active = true; fetch('https://world.openfoodfacts.org/api/v2/product/' + encodeURIComponent(code) + '?fields=product_name,product_name_tr,brands,image_url').then(r => r.json()).then(data => { if (active) setInfo({ name: data.product?.product_name_tr || data.product?.product_name, brand: data.product?.brands, image: data.product?.image_url }); }).catch(() => undefined); return () => { active = false; }; }, [code]);
  const statuses = [{ label:'Uygun', icon:'checkmark', bg:'#E3F6E7', color:'#178144' }, { label:'Dikkat', icon:'alert', bg:'#FFF1CF', color:'#C77900' }, { label:'Uygun Değil', icon:'close', bg:'#FDE6E6', color:'#C52D2D' }]; const status = statuses[index % statuses.length];
  return <Pressable onPress={() => onOpen(code)} style={s.row}><View style={s.productImage}>{info.image ? <Image source={{ uri: info.image }} style={s.image} resizeMode="contain"/> : <Ionicons name="cube-outline" size={25} color="#92A49A"/>}</View><View style={s.rowCopy}><Text numberOfLines={1} style={s.name}>{info.name || 'Ürün aranıyor…'}</Text><Text numberOfLines={1} style={s.brand}>{info.brand || 'Barkod: ' + code}</Text><Text style={s.date}>Bugün · otomatik kaydedildi</Text></View><View style={s.status}><View style={[s.statusIcon, { backgroundColor: status.bg }]}><Ionicons name={status.icon as React.ComponentProps<typeof Ionicons>['name']} size={15} color={status.color}/></View><Text style={[s.statusText, { color: status.color }]}>{status.label}</Text></View><Ionicons name="chevron-forward" size={17} color="#8A9A90"/></Pressable>;
}
const s = StyleSheet.create({ page:{padding:18,paddingBottom:110,backgroundColor:'#F7FBF5',gap:13},top:{flexDirection:'row',justifyContent:'space-between',alignItems:'center'},kicker:{fontSize:10,fontWeight:'900',letterSpacing:.9,color:colors.brand},title:{fontSize:27,fontWeight:'900',color:colors.ink,marginTop:3},total:{width:36,height:36,borderRadius:18,alignItems:'center',justifyContent:'center',backgroundColor:'#DDF2E1'},totalText:{fontWeight:'900',color:colors.brand},filters:{flexDirection:'row',gap:7},filter:{paddingHorizontal:10,paddingVertical:8,borderRadius:13,backgroundColor:'#fff'},filterOn:{backgroundColor:colors.brand},filterText:{fontSize:10,fontWeight:'800',color:'#6E7C73'},filterTextOn:{color:'#fff'},list:{gap:9},row:{minHeight:78,padding:9,borderRadius:18,backgroundColor:'#fff',flexDirection:'row',alignItems:'center',gap:9,borderWidth:1,borderColor:'#E5EEE5'},productImage:{width:54,height:58,borderRadius:12,backgroundColor:'#F3F7F1',alignItems:'center',justifyContent:'center',overflow:'hidden'},image:{width:52,height:56},rowCopy:{flex:1,minWidth:0},name:{fontSize:13,fontWeight:'900',color:colors.ink},brand:{fontSize:11,color:'#64736A',marginTop:2},date:{fontSize:9,color:'#9AA69E',marginTop:4},status:{alignItems:'center',width:51},statusIcon:{width:25,height:25,borderRadius:13,alignItems:'center',justifyContent:'center'},statusText:{fontSize:8,textAlign:'center',fontWeight:'900',marginTop:3},empty:{flex:1,alignItems:'center',justifyContent:'center',backgroundColor:'#F7FBF5',padding:30},emptyTitle:{fontSize:20,fontWeight:'900',color:colors.ink,marginTop:10},emptyText:{fontSize:13,color:'#708076',textAlign:'center',marginTop:5} });
