import { Ionicons } from '@expo/vector-icons';
import React from 'react';
import { ImageBackground, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { colors } from '../theme';

const background = require('../../assets/branding/wellness-background-v1.png');
export function HomeScreen({ onScan, selected, scans, onProfile }: { onScan: () => void; selected: string[]; scans: string[]; onProfile: () => void }) {
  const summary = selected.length ? selected.slice(0, 2).join(' · ') : 'Sağlık tercihlerini ekleyerek sonuçları kişiselleştir.';
  return <ImageBackground source={background} resizeMode="cover" style={s.fill} imageStyle={s.bg}><ScrollView contentContainerStyle={s.page} showsVerticalScrollIndicator={false}>
    <View style={s.intro}><Text style={s.eyebrow}>GÜNLÜK SAĞLIK ASİSTANIN</Text><Text style={s.title}>Daha bilinçli{'\n'}seçimler yap.</Text><Text style={s.copy}>Ürünün içeriğini sağlık profilin için saniyeler içinde değerlendir.</Text></View>
    <View style={s.scanCard}><View style={s.scanGlow}><Ionicons name="barcode-outline" size={42} color="#fff" /></View><Text style={s.scanTitle}>Ürünü tara</Text><Text style={s.scanCopy}>Barkodu okut, içerik ve besin değerlerini sana göre yorumlayalım.</Text><Pressable onPress={onScan} style={s.scanButton}><Ionicons name="scan-outline" size={20} color="#fff" /><Text style={s.scanButtonText}>Barkod Tara</Text></Pressable></View>
    <Pressable onPress={onProfile} style={s.profileCard}><View style={s.profileIcon}><Ionicons name="heart-outline" size={22} color="#CA4F5A" /></View><View style={s.profileText}><Text style={s.profileTitle}>{selected.length ? String(selected.length) + ' sağlık tercihi aktif' : 'Sağlık profilini tamamla'}</Text><Text numberOfLines={2} style={s.profileCopy}>{summary}</Text></View><Ionicons name="chevron-forward" size={20} color={colors.brand} /></Pressable>
    <View style={s.sectionHead}><Text style={s.sectionTitle}>Son taramalar</Text><Text style={s.sectionHint}>{scans.length ? 'Tümünü gör' : 'Henüz yok'}</Text></View>
    <View style={s.historyCard}><View style={[s.historyIcon, scans.length ? s.historyDone : undefined]}><Ionicons name={scans.length ? 'checkmark' : 'leaf-outline'} size={21} color={scans.length ? '#fff' : colors.brand} /></View><View><Text style={s.historyTitle}>{scans.length ? 'Son ürün kaydedildi' : 'İlk ürününü taramaya hazır mısın?'}</Text><Text style={s.historyCopy}>{scans.length ? 'Barkod: ' + scans[0] : 'Geçmişin burada güvenle saklanır.'}</Text></View></View>
    <Text style={s.note}>Bu uygulama tıbbi tavsiye veya tanı yerine geçmez.</Text>
  </ScrollView></ImageBackground>;
}
const s = StyleSheet.create({ fill:{flex:1,backgroundColor:'#FFFDF7'},bg:{opacity:.38},page:{padding:18,paddingBottom:120,gap:16},intro:{paddingTop:14},eyebrow:{fontSize:10,fontWeight:'900',letterSpacing:1.15,color:colors.brand},title:{fontSize:32,lineHeight:37,color:colors.ink,fontWeight:'900',marginTop:7},copy:{color:'#52695C',fontSize:14,lineHeight:20,marginTop:7,maxWidth:285},scanCard:{backgroundColor:'rgba(16,104,70,.96)',borderRadius:30,padding:22,shadowColor:'#0B4D32',shadowOpacity:.22,shadowRadius:16,elevation:5},scanGlow:{width:65,height:65,borderRadius:23,alignItems:'center',justifyContent:'center',backgroundColor:'rgba(255,255,255,.16)'},scanTitle:{fontSize:25,fontWeight:'900',color:'#fff',marginTop:15},scanCopy:{fontSize:14,lineHeight:20,color:'#DDF2E5',marginTop:5,maxWidth:280},scanButton:{height:52,marginTop:20,backgroundColor:'#F9C555',borderRadius:17,alignItems:'center',justifyContent:'center',flexDirection:'row',gap:8},scanButtonText:{color:'#173529',fontSize:16,fontWeight:'900'},profileCard:{padding:15,borderRadius:22,flexDirection:'row',alignItems:'center',gap:11,backgroundColor:'rgba(255,255,255,.92)',borderWidth:1,borderColor:'#EAE7DC'},profileIcon:{width:44,height:44,borderRadius:16,backgroundColor:'#FCE9E9',alignItems:'center',justifyContent:'center'},profileText:{flex:1},profileTitle:{color:colors.ink,fontSize:15,fontWeight:'900'},profileCopy:{color:'#65766C',fontSize:12,lineHeight:17,marginTop:3},sectionHead:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',marginTop:4},sectionTitle:{fontSize:19,fontWeight:'900',color:colors.ink},sectionHint:{fontSize:11,fontWeight:'800',color:colors.brand},historyCard:{backgroundColor:'rgba(255,255,255,.9)',padding:16,borderRadius:22,flexDirection:'row',alignItems:'center',gap:12,borderWidth:1,borderColor:'#ECE9DE'},historyIcon:{width:46,height:46,borderRadius:16,backgroundColor:'#EAF5E8',alignItems:'center',justifyContent:'center'},historyDone:{backgroundColor:'#35A867'},historyTitle:{color:colors.ink,fontWeight:'900',fontSize:15},historyCopy:{color:'#6B7B71',fontSize:12,marginTop:4},note:{textAlign:'center',fontSize:10,color:'#708075',marginTop:2} });
