import React, { useEffect, useState } from 'react';
import { Animated, Easing, Image, ImageBackground, StyleSheet, Text, View } from 'react-native';
import { colors } from '../theme';
const background = require('../../assets/branding/wellness-background-v1.png');
const appIcon = require('../../assets/branding/footandhealth-app-icon.png');
export function LoadingScreen() {
  const [drift] = useState(() => new Animated.Value(0)); const [spin] = useState(() => new Animated.Value(0));
  useEffect(() => { const moving = Animated.loop(Animated.sequence([Animated.timing(drift,{toValue:1,duration:2100,easing:Easing.inOut(Easing.quad),useNativeDriver:true}),Animated.timing(drift,{toValue:0,duration:2100,easing:Easing.inOut(Easing.quad),useNativeDriver:true})])); const turning = Animated.loop(Animated.timing(spin,{toValue:1,duration:3000,easing:Easing.linear,useNativeDriver:true})); moving.start(); turning.start(); return () => { moving.stop(); turning.stop(); }; }, [drift, spin]);
  const translateX = drift.interpolate({ inputRange:[0,1], outputRange:[-25,42] }); const rotate = spin.interpolate({ inputRange:[0,1], outputRange:['0deg','360deg'] });
  return <ImageBackground source={background} style={s.page} imageStyle={s.bg}><Animated.View style={[s.fruit,{transform:[{translateX},{rotate}]}]}><Text style={s.fruitText}>🍊</Text></Animated.View><Animated.View style={[s.fruit2,{transform:[{translateX:Animated.multiply(translateX,-.7)},{rotate}]}]}><Text style={s.fruitText}>🫐</Text></Animated.View><View style={s.center}><Image source={appIcon} style={s.icon}/><Text style={s.brand}>GIDA PUSULASI</Text><Text style={s.copy}>Sana özel sağlıklı seçimler hazırlanıyor</Text><View style={s.dots}><View style={s.dot}/><View style={[s.dot,s.dotSoft]}/><View style={[s.dot,s.dotSoft]}/></View></View></ImageBackground>;
}
const s=StyleSheet.create({page:{flex:1,alignItems:'center',justifyContent:'center',backgroundColor:'#F9F6EC',overflow:'hidden'},bg:{opacity:.68},center:{alignItems:'center',paddingHorizontal:40},icon:{width:82,height:82,borderRadius:27,shadowColor:'#1D613E',shadowOpacity:.22,shadowRadius:12},brand:{fontSize:16,fontWeight:'900',letterSpacing:1.5,color:colors.ink,marginTop:16},copy:{fontSize:13,color:'#5E7466',textAlign:'center',lineHeight:19,marginTop:8},dots:{flexDirection:'row',gap:8,marginTop:24},dot:{width:9,height:9,borderRadius:5,backgroundColor:colors.brand},dotSoft:{opacity:.28},fruit:{position:'absolute',top:'21%',left:'8%'},fruit2:{position:'absolute',top:'66%',right:'11%'},fruitText:{fontSize:43}});
