import React from 'react';
import { ScrollView, StyleSheet, Text, View } from 'react-native';
import { AppButton, Card } from '../components/ui';
import { colors, spacing } from '../theme';

export function LoginScreen({ onContinue }: { onContinue: () => void }) { return <View style={styles.center}><Text style={styles.logo}>FOOT & HEALTH</Text><Text style={styles.title}>Sağlıklı seçimler,{"\n"}daha net bilgiler.</Text><Text style={styles.copy}>Gıda ürünlerini tarayın, tercihlerinize göre içerik verilerini görün.</Text><View style={styles.grow}/><AppButton label="Devam Et" onPress={onContinue}/><Text style={styles.legal}>Giriş ve kayıt ekranları Phase 2&apos;de eklenecek.</Text></View>; }
export function OnboardingScreen({ onComplete }: { onComplete: () => void }) { return <ScrollView contentContainerStyle={styles.scroll}><Text style={styles.kicker}>KİŞİSELLEŞTİRME</Text><Text style={styles.title}>Sağlık tercihlerinizi seçin</Text><Text style={styles.copy}>Ürün verilerindeki önemli bilgileri bu tercihlere göre öne çıkaracağız.</Text><Card><Text style={styles.cardTitle}>Tercih seçimi</Text><Text style={styles.cardCopy}>Çölyak, diyabet, hipertansiyon ve diğer koşullar için çoklu seçim kartları Phase 2’de eklenecek.</Text></Card><AppButton label="Devam Et" onPress={onComplete}/></ScrollView>; }
export function ScannerScreen({ onResult }: { onResult: () => void }) { return <View style={[styles.center, styles.scanner]}><Text style={styles.logo}>BARKOD TARA</Text><View style={styles.camera}><Text style={styles.scanMark}>▥</Text><Text style={styles.cameraCopy}>Kamerayı ürün barkoduna tutun</Text></View><AppButton label="Demo sonucu göster" onPress={onResult} tone="soft"/><Text style={styles.legal}>Kamera izni ve EAN/UPC tarama Phase 4’te eklenecek.</Text></View>; }
export function ResultScreen({ onClose }: { onClose: () => void }) { return <ScrollView contentContainerStyle={styles.scroll}><Text style={styles.kicker}>ÜRÜN SONUCU</Text><Card><View style={styles.productImage}><Text style={styles.productImageText}>Ürün görseli</Text></View><Text style={styles.cardTitle}>Ürün adı</Text><Text style={styles.cardCopy}>Marka · Gramaj</Text></Card><Card style={{ backgroundColor: '#FFF7E9', borderColor: '#F3D8AB' }}><Text style={styles.warning}>● Dikkat</Text><Text style={styles.cardTitle}>Sağlık özeti hazırlanıyor</Text><Text style={styles.cardCopy}>Değerlendirme, seçilen tercihler ve doğrulanmış ürün verileriyle gösterilecek.</Text></Card><Text style={styles.legal}>Bu uygulama tıbbi tavsiye yerine geçmez.</Text><AppButton label="Ana sayfaya dön" onPress={onClose}/></ScrollView>; }
const styles = StyleSheet.create({ center: { flex: 1, padding: spacing.lg, backgroundColor: colors.canvas }, scroll: { padding: spacing.lg, gap: spacing.md, paddingBottom: 80, backgroundColor: colors.canvas, minHeight: '100%' }, logo: { color: colors.brand, fontSize: 13, letterSpacing: 1.5, fontWeight: '900' }, kicker: { color: colors.brand, fontSize: 12, fontWeight: '900', letterSpacing: 1.1 }, title: { color: colors.ink, fontSize: 29, lineHeight: 36, fontWeight: '900', marginTop: 14 }, copy: { color: colors.muted, fontSize: 16, lineHeight: 23, marginTop: 12 }, grow: { flex: 1 }, legal: { color: colors.muted, textAlign: 'center', fontSize: 12, marginTop: 14 }, cardTitle: { color: colors.ink, fontSize: 18, fontWeight: '800', marginTop: 12 }, cardCopy: { color: colors.muted, lineHeight: 21, marginTop: 7 }, scanner: { gap: spacing.md }, camera: { flex: 1, width: '100%', backgroundColor: '#16221C', borderRadius: 26, alignItems: 'center', justifyContent: 'center', borderWidth: 2, borderColor: colors.brand }, scanMark: { color: '#D5F7E1', fontSize: 72, fontWeight: '900' }, cameraCopy: { color: '#fff', marginTop: 18, fontWeight: '700' }, productImage: { height: 152, borderRadius: 12, backgroundColor: colors.canvas, alignItems: 'center', justifyContent: 'center' }, productImageText: { color: colors.muted }, warning: { color: colors.orange, fontWeight: '900' } });
