import React, { useEffect, useState } from 'react';
import { Image, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { colors } from '../theme';

type Product = { name?: string; brand?: string; image?: string; ingredients?: string; energy?: string; carbohydrates?: string; sugars?: string; salt?: string };
function useProduct(code: string) { const [product,setProduct]=useState<Product>({}); useEffect(()=>{let active=true;fetch('https://world.openfoodfacts.org/api/v2/product/'+encodeURIComponent(code)+'?fields=product_name,product_name_tr,brands,image_url,ingredients_text,nutriments').then(r=>r.json()).then(d=>{if(!active)return;const p=d.product;setProduct({name:p?.product_name_tr||p?.product_name,brand:p?.brands,image:p?.image_url,ingredients:p?.ingredients_text,energy:p?.nutriments?.['energy-kcal_100g'],carbohydrates:p?.nutriments?.carbohydrates_100g,sugars:p?.nutriments?.sugars_100g,salt:p?.nutriments?.salt_100g})}).catch(()=>undefined);return()=>{active=false}},[code]); return product; }
export function ProductResultScreen({barcode,onClose,onProfile,selected}:{barcode:string;onClose:()=>void;onProfile:()=>void;selected:string[]}){const p=useProduct(barcode);const value=(v?:string)=>v?String(v)+' g':'Bilinmiyor';return <ScrollView contentContainerStyle={s.page}><View style={s.top}><Pressable onPress={onClose}><Text style={s.back}>‹</Text></Pressable><Text style={s.title}>Ürün sonucu</Text><Text style={s.saved}>Otomatik kaydedildi ✓</Text></View><View style={s.product}>{p.image?<Image source={{uri:p.image}} style={s.image} resizeMode="contain"/>:<View style={s.placeholder}><Text style={s.placeholderText}>ÜRÜN</Text></View>}<View style={{flex:1}}><Text style={s.name}>{p.name||'Ürün aranıyor…'}</Text><Text style={s.brand}>{p.brand||'Barkod: '+barcode}</Text><Text style={s.code}>▥ {barcode}</Text></View></View><View style={s.notice}><Text style={s.noticeIcon}>!</Text><View style={{flex:1}}><Text style={s.noticeTitle}>Sağlık profilin için bilgi</Text><Text style={s.noticeText}>{selected.length?'Seçili sağlık durumlarını ürün etiketiyle birlikte değerlendir.':'Profilinden sağlık tercihlerini ekleyebilirsin.'}</Text></View></View><View style={s.section}><Text style={s.sectionTitle}>Besin değerleri · 100 g</Text></View><View style={s.card}><Line title="Enerji" value={p.energy?String(p.energy)+' kcal':'Bilinmiyor'}/><Line title="Karbonhidrat" value={value(p.carbohydrates)}/><Line title="Şeker" value={value(p.sugars)}/><Line title="Tuz" value={value(p.salt)}/></View><View style={s.section}><Text style={s.sectionTitle}>İçindekiler</Text><Pressable onPress={onProfile}><Text style={s.edit}>Profili düzenle</Text></Pressable></View><View style={s.card}><Text style={s.ingredients}>{p.ingredients||'Bu ürünün içerik bilgisi veri kaynağında bulunamadı. Ambalaj etiketini kontrol edin.'}</Text></View><Text style={s.footer}>Veriler Open Food Facts kaynağından gelir; ambalaj etiketi önceliklidir.</Text></ScrollView>}
function Line({title,value}:{title:string;value:string}){return <View style={s.line}><Text style={s.lineTitle}>{title}</Text><Text style={s.lineValue}>{value}</Text></View>}
const s=StyleSheet.create({page:{padding:18,gap:13,paddingBottom:50,backgroundColor:'#FFFDF7'},top:{flexDirection:'row',alignItems:'center',justifyContent:'space-between'},back:{fontSize:42,lineHeight:35,color:colors.brand},title:{fontSize:24,fontWeight:'900',color:colors.ink},saved:{fontSize:10,fontWeight:'800',color:colors.brand},product:{flexDirection:'row',gap:14,alignItems:'center'},image:{width:112,height:145,borderRadius:18,backgroundColor:'#fff'},placeholder:{width:112,height:145,borderRadius:18,backgroundColor:'#8DBD67',justifyContent:'center',alignItems:'center'},placeholderText:{fontWeight:'900',color:'#fff'},name:{fontSize:21,lineHeight:25,fontWeight:'900',color:colors.ink},brand:{color:colors.muted,marginTop:4},code:{backgroundColor:'#E8F5FF',color:colors.ink,fontSize:12,padding:8,borderRadius:10,overflow:'hidden',marginTop:10},notice:{backgroundColor:'#FFF0EF',padding:14,borderRadius:18,flexDirection:'row',gap:10},noticeIcon:{width:31,height:31,borderRadius:16,backgroundColor:'#D9423A',color:'#fff',fontWeight:'900',fontSize:20,textAlign:'center',paddingTop:3},noticeTitle:{color:'#A72927',fontSize:16,fontWeight:'900'},noticeText:{color:colors.muted,fontSize:13,lineHeight:18,marginTop:3},section:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',marginTop:5},sectionTitle:{color:colors.ink,fontWeight:'900',fontSize:18},edit:{color:colors.brand,fontSize:12,fontWeight:'800'},card:{backgroundColor:'#EDF7FD',padding:14,borderRadius:17},line:{flexDirection:'row',justifyContent:'space-between',paddingVertical:7,borderBottomWidth:1,borderColor:'#D4E6EF'},lineTitle:{color:colors.muted},lineValue:{color:colors.ink,fontWeight:'900'},ingredients:{color:colors.muted,lineHeight:20},footer:{color:colors.muted,fontSize:11,textAlign:'center'}});
